### ISSUE TITLE
Tagging of sub-chapters

### ISSUE THREAD

**Issue by drgrigg** [lukasbystricky/w-e-b-du-bois_darkwater#1]
Interesting structure this book has!

I think your treatment of the interleaved passages as sub-chapters is fine (I can't see how else you could do it, and your structure results in a ToC like the one in the scans), but so far as I can see most of them should be tagged as z3998:fiction, certainly those already tagged as se:short-story or z3998:poem. 

I wasn't sure about your tagging of the "Litany" at the end of the first chapter as z3998:hymn. z3998:hymn is derived from z3998:song, so should be a song, which this isn't. In this case I would just remove that tag.

**Comment by drgrigg** [comment]
If you drop z3998:hymn then you should also drop it in local.css

**Comment by drgrigg** [comment]
Hmmm, now I look more closely at the Litany I'll need to think about it some more. I see what you're trying to do.

**Comment by drgrigg** [comment]
I do still think that z3998:hymn is wrong here. I think this could be a rare case where named css classes might work better, eg class="call" and class="response". I think we might bounce this to Alex for his decision.

**Comment by drgrigg** [comment]
@acabal, can we get your opinion about this issue of the formatting of the "Litany" subchapter at the end of chapter-1? Is this a case where Lucas would be better using named css classes?

**Comment by acabal** [comment]
I don't think it's a hymn, as it's not a song or verse. So you can remove verse formatting. This can just be regular `<p>`s with a class to indicate paragraphs that are italicized.

**Comment by lukasbystricky** [comment]
Ok, as I mentioned on Google I think a prayer/chant inflection could be useful eventually, but this also works.
